### ISSUE TITLE
Variadic broken logic

### ISSUE THREAD

**Issue by agdobrynin** [agdobrynin/di-container#106]
Реализованная для `variadic` аргументов и параметров логика не правильная, так как нужно точно указывать количество аргументов а не опираться на array.
Если нужна какая-то более упрощенная логика то надо будет доавлять функционал именно для variadic типов.

Убрать магию преобразований и остановится на логичном поведении.

```php
namespace App\Rules;

interface RuleInterface {}

class RuleA implements RuleInterface {}
class RuleB implements RuleInterface {}

class RuleGenerator {
    private iterable $rules;

    public function __construct(
        // 🚩 тут ожидается что вернётся только один элемент
        // 🚩 и тип у него должен быть RuleInterface
        #[Inject('services.rules')]
        RuleInterface ...$inputRule
    ) {
        $this->rules = $inputRule;
    }
}

// определения для контейнера
$definitions = [
    // 🔥 запрашиваемый контейнер вернут массив 
    // 🔥 и все кто запрашивает его должны ожидать массив
    'services.rules' => diCallable(
        // Автоматически внедрит зависимости этой callback функции
        static function (App\Rules\RuleB $b, App\Rules\RuleA $a) {
            return [$b, $a]; // вернуть массив определений для аргумента переменной длины.
        }
    ),
];

$container = (new DiContainerFactory())->make($definitions);

```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the DiContainer class to properly handle variadic arguments. Removed the automatic array wrapping for variadic parameters and ensured that the exact number of arguments is respected. Updated the ParametersResolverTrait to handle variadic parameters correctly.

You can review changes in this commit: https://github.com/mnmnk43434/agdobrynin-di-container-106/commit/113981db9bae57d01ab94bd87e72b5b61a1e08c4.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
